stages:
  - build
  - push

cache:
  paths:
  - node_modules/

test_build:
  image: node:latest
  stage: build
  script:
   - yarn
   - yarn run build

push_master:
  image: docker.reallserver.cn/public/docker-git
  stage: push
  only:
  - master
  script:
  - git push --set-upstream https://${github_key}@github.com/pomment/frontend.git HEAD:master
